#
#  Podfile
#  WYPayBusinessModule
#
#  Created by weiyi on 2020/11/7.
#  Copyright (c) 2020 wwyy. All rights reserved.
#

source 'http://dev45.gitlab.miyabaobei.com/iOS/MIASpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'WYPayBusinessModule' do
    platform :ios, '8.0'
    inhibit_all_warnings!

end
